# relio/sdkgen.py
"""Generate TypeScript and Python SDKs (types + typed client) from the backend's
OpenAPI schema, so every client mirrors the one source of truth (Pydantic).

Dependency-light and offline: walks the schema dict the FastAPI app already
produces — no external codegen toolchain.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #


def _ref_name(schema: dict) -> str:
    return schema["$ref"].rsplit("/", 1)[-1]


def _camel(snake: str) -> str:
    head, *rest = snake.split("_")
    return head + "".join(p.capitalize() for p in rest)


def _success_response(op: dict) -> dict | None:
    for code in ("200", "201"):
        resp = op.get("responses", {}).get(code)
        if resp:
            return resp.get("content", {}).get("application/json", {}).get("schema")
    return None


# --------------------------------------------------------------------------- #
# TypeScript
# --------------------------------------------------------------------------- #


def _ts_type(schema: dict | None) -> str:
    if not schema:
        return "any"
    if "$ref" in schema:
        return _ref_name(schema)
    if "allOf" in schema:
        return _ts_type(schema["allOf"][0])
    if "anyOf" in schema:
        parts = [_ts_type(s) for s in schema["anyOf"]]
        return " | ".join(dict.fromkeys(parts))  # de-dupe, keep order
    if "enum" in schema:
        return " | ".join(_ts_literal(v) for v in schema["enum"])
    t = schema.get("type")
    if t == "array":
        return f"{_ts_type(schema.get('items'))}[]"
    if t == "object":
        return "Record<string, any>"
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    return "any"


def _ts_literal(v: Any) -> str:
    return f'"{v}"' if isinstance(v, str) else str(v)


def generate_ts_types(openapi: dict) -> str:
    schemas = openapi.get("components", {}).get("schemas", {})
    lines = ["// AUTO-GENERATED by `relio sdk`. Do not edit by hand.", ""]
    for name, schema in schemas.items():
        if "enum" in schema:
            union = " | ".join(_ts_literal(v) for v in schema["enum"])
            lines.append(f"export type {name} = {union};")
            lines.append("")
            continue
        if schema.get("type") == "object":
            required = set(schema.get("required", []))
            lines.append(f"export interface {name} {{")
            for prop, pschema in schema.get("properties", {}).items():
                opt = "" if prop in required else "?"
                lines.append(f"  {prop}{opt}: {_ts_type(pschema)};")
            lines.append("}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


_TS_CLIENT_PREAMBLE = '''\
// AUTO-GENERATED by `relio sdk`. Do not edit by hand.
import type {{ {imports} }} from "./types";

export class RelioClient {{
  constructor(private baseUrl: string = "", private apiKey?: string) {{}}

  private _headers(json: boolean): Record<string, string> {{
    const h: Record<string, string> = {{}};
    if (json) h["Content-Type"] = "application/json";
    if (this.apiKey) h["Authorization"] = `Bearer ${{this.apiKey}}`;
    return h;
  }}

  private async _request(method: string, path: string, body?: any, query?: Record<string, any>): Promise<any> {{
    let qs = "";
    if (query) {{
      const p = new URLSearchParams();
      for (const [k, v] of Object.entries(query)) if (v !== undefined && v !== null) p.set(k, String(v));
      const s = p.toString();
      if (s) qs = "?" + s;
    }}
    const res = await fetch(this.baseUrl + path + qs, {{
      method,
      headers: this._headers(body !== undefined),
      body: body !== undefined ? JSON.stringify(body) : undefined,
    }});
    if (!res.ok) throw new Error(`Relio ${{method}} ${{path}} -> ${{res.status}}`);
    const text = await res.text();
    return text ? JSON.parse(text) : null;
  }}

  private async _requestForm(method: string, path: string, form: FormData): Promise<any> {{
    // multipart/form-data: let the browser set the Content-Type + boundary.
    const res = await fetch(this.baseUrl + path, {{ method, headers: this._headers(false), body: form }});
    if (!res.ok) throw new Error(`Relio ${{method}} ${{path}} -> ${{res.status}}`);
    const text = await res.text();
    return text ? JSON.parse(text) : null;
  }}

  private async *_stream(method: string, path: string, body?: any): AsyncGenerator<string> {{
    const res = await fetch(this.baseUrl + path, {{
      method, headers: this._headers(body !== undefined),
      body: body !== undefined ? JSON.stringify(body) : undefined,
    }});
    const reader = res.body!.getReader();
    const dec = new TextDecoder();
    let buf = "";
    while (true) {{
      const {{ done, value }} = await reader.read();
      if (done) break;
      buf += dec.decode(value, {{ stream: true }});
      let i: number;
      while ((i = buf.indexOf("\\n\\n")) !== -1) {{
        const f = buf.slice(0, i).trim();
        buf = buf.slice(i + 2);
        if (!f.startsWith("data:")) continue;
        const p = JSON.parse(f.slice(f.indexOf(":") + 1).trim());
        yield (p.delta ?? p.text ?? "");
      }}
    }}
  }}

  async *chat(body: ChatRequest): AsyncGenerator<string> {{
    const res = await fetch(this.baseUrl + "/api/chat", {{
      method: "POST",
      headers: this._headers(true),
      body: JSON.stringify(body),
    }});
    const reader = res.body!.getReader();
    const dec = new TextDecoder();
    let buf = "";
    while (true) {{
      const {{ done, value }} = await reader.read();
      if (done) break;
      buf += dec.decode(value, {{ stream: true }});
      let i: number;
      while ((i = buf.indexOf("\\n\\n")) !== -1) {{
        const f = buf.slice(0, i).trim();
        buf = buf.slice(i + 2);
        if (!f.startsWith("data:")) continue;
        const p = JSON.parse(f.slice(f.indexOf(":") + 1).trim());
        if (p.delta) yield p.delta;
      }}
    }}
  }}
'''


def _op_inputs(path: str, op: dict) -> tuple[list[str], str | None, list[dict]]:
    """Return (path_param_names, body_type_name | None, query_params)."""
    path_params = [
        p["name"] for p in op.get("parameters", []) if p.get("in") == "path"
    ]
    query_params = [p for p in op.get("parameters", []) if p.get("in") == "query"]
    body_type = None
    rb = op.get("requestBody")
    if rb:
        schema = rb.get("content", {}).get("application/json", {}).get("schema", {})
        if "$ref" in schema:
            body_type = _ref_name(schema)
    return path_params, body_type, query_params


def _is_streaming(op: dict) -> bool:
    """True if the endpoint streams Server-Sent Events (declares a
    `text/event-stream` success response) — emit a generator instead of a
    one-shot request."""
    for code in ("200", "201"):
        content = op.get("responses", {}).get(code, {}).get("content", {})
        if "text/event-stream" in content:
            return True
    return False


def _multipart_fields(op: dict) -> list[str] | None:
    """If the request body is `multipart/form-data`, return its field names
    (files + form fields); else None. Drives file-upload method generation."""
    rb = op.get("requestBody")
    if not rb:
        return None
    schema = rb.get("content", {}).get("multipart/form-data", {}).get("schema")
    if schema is None:
        return None
    return list(schema.get("properties", {}).keys())


@dataclass
class _ClientOp:
    """A language-agnostic plan for one endpoint. Both client generators classify
    operations once here, then only differ in how they render each `kind`."""
    op_id: str
    method: str            # upper-cased HTTP verb
    path: str
    path_params: list[str]
    body_type: str | None
    query_params: list[dict]
    kind: str              # "plain" | "stream" | "multipart"
    success: dict | None   # success-response schema


def _plan_operations(openapi: dict) -> list[_ClientOp]:
    """Walk the OpenAPI paths into `_ClientOp`s, skipping the hand-written chat
    method. The single source of the chat-skip + multipart/stream classification."""
    plans: list[_ClientOp] = []
    for path, item in openapi.get("paths", {}).items():
        for method, op in item.items():
            op_id = op.get("operationId")
            if not op_id or op_id == "chat":  # chat is hand-written in the preamble
                continue
            path_params, body_type, query_params = _op_inputs(path, op)
            if _multipart_fields(op) is not None:
                kind = "multipart"
            elif _is_streaming(op):
                kind = "stream"
            else:
                kind = "plain"
            plans.append(
                _ClientOp(
                    op_id=op_id, method=method.upper(), path=path,
                    path_params=path_params, body_type=body_type,
                    query_params=query_params, kind=kind, success=_success_response(op),
                )
            )
    return plans


def generate_ts_client(openapi: dict) -> str:
    schemas = openapi.get("components", {}).get("schemas", {})
    imports = ", ".join(sorted(schemas.keys()))
    out = [_TS_CLIENT_PREAMBLE.format(imports=imports)]
    for op in _plan_operations(openapi):
        name = _camel(op.op_id)
        url = op.path
        for p in op.path_params:
            url = url.replace("{" + p + "}", "${" + _camel(p) + "}")
        path_args = [f"{_camel(p)}: string" for p in op.path_params]
        ret = _ts_type(op.success)

        if op.kind == "multipart":
            args = path_args + ["form: FormData"]
            out.append(
                f"  async {name}({', '.join(args)}): Promise<{ret}> {{\n"
                f'    return this._requestForm("{op.method}", `{url}`, form);\n'
                f"  }}\n"
            )
        elif op.kind == "stream":
            args = path_args + ([f"body: {op.body_type}"] if op.body_type else [])
            body_arg = "body" if op.body_type else "undefined"
            out.append(
                f"  async *{name}({', '.join(args)}): AsyncGenerator<string> {{\n"
                f'    yield* this._stream("{op.method}", `{url}`, {body_arg});\n'
                f"  }}\n"
            )
        else:
            args = list(path_args)
            if op.body_type:
                args.append(f"body: {op.body_type}")
            if op.query_params:
                fields = [
                    f"{q['name']}{'' if q.get('required') else '?'}: {_ts_type(q.get('schema'))}"
                    for q in op.query_params
                ]
                args.append("query: { " + "; ".join(fields) + " }")
            call = [f'"{op.method}"', f"`{url}`", "body" if op.body_type else "undefined"]
            if op.query_params:
                call.append("query")
            out.append(
                f"  async {name}({', '.join(args)}): Promise<{ret}> {{\n"
                f"    return this._request({', '.join(call)});\n"
                f"  }}\n"
            )
    out.append("}\n")
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# Python
# --------------------------------------------------------------------------- #


def _py_type(schema: dict | None) -> str:
    if not schema:
        return "Any"
    if "$ref" in schema:
        return f'"{_ref_name(schema)}"'
    if "allOf" in schema:
        return _py_type(schema["allOf"][0])
    if "anyOf" in schema:
        parts = [s for s in schema["anyOf"] if s.get("type") != "null"]
        inner = " | ".join(dict.fromkeys(_py_type(s) for s in parts)) or "Any"
        if any(s.get("type") == "null" for s in schema["anyOf"]):
            return f"Optional[{inner}]"
        return inner
    if "enum" in schema:
        return "Literal[" + ", ".join(repr(v) for v in schema["enum"]) + "]"
    t = schema.get("type")
    if t == "array":
        return f"List[{_py_type(schema.get('items'))}]"
    if t == "object":
        return "Dict[str, Any]"
    if t == "string":
        return "str"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "null":
        return "None"
    return "Any"


def generate_py_types(openapi: dict) -> str:
    schemas = openapi.get("components", {}).get("schemas", {})
    lines = [
        "# AUTO-GENERATED by `relio sdk`. Do not edit by hand.",
        "from __future__ import annotations",
        "",
        "from typing import Any, Dict, List, Literal, Optional, TypedDict",
        "",
    ]
    for name, schema in schemas.items():
        if "enum" in schema:
            union = ", ".join(repr(v) for v in schema["enum"])
            lines.append(f"{name} = Literal[{union}]")
            lines.append("")
            continue
        if schema.get("type") == "object":
            lines.append(f"class {name}(TypedDict, total=False):")
            props = schema.get("properties", {})
            if not props:
                lines.append("    pass")
            for prop, pschema in props.items():
                lines.append(f"    {prop}: {_py_type(pschema)}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


_PY_CLIENT_PREAMBLE = '''\
# AUTO-GENERATED by `relio sdk`. Do not edit by hand.
from __future__ import annotations

import json
import urllib.parse
import urllib.request
import uuid
from typing import Any, Dict, Iterator, Optional, Tuple, Union


class RelioClient:
    def __init__(self, base_url: str = "http://localhost:8000", api_key: Optional[str] = None) -> None:
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key

    def _headers(self, json_body: bool) -> Dict[str, str]:
        h: Dict[str, str] = {}
        if json_body:
            h["Content-Type"] = "application/json"
        if self.api_key:
            h["Authorization"] = f"Bearer {self.api_key}"
        return h

    def _request(self, method: str, path: str, body: Any = None, query: Optional[Dict[str, Any]] = None) -> Any:
        url = self.base_url + path
        if query:
            clean = {k: v for k, v in query.items() if v is not None}
            if clean:
                url += "?" + urllib.parse.urlencode(clean)
        data = json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(url, data=data, headers=self._headers(body is not None), method=method)
        with urllib.request.urlopen(req) as resp:
            text = resp.read().decode()
        return json.loads(text) if text else None

    def _stream(self, method: str, path: str, body: Any = None) -> Iterator[str]:
        data = json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(
            self.base_url + path, data=data, headers=self._headers(body is not None), method=method
        )
        with urllib.request.urlopen(req) as resp:
            for raw in resp:
                line = raw.decode().strip()
                if not line.startswith("data:"):
                    continue
                payload = json.loads(line[len("data:"):].strip())
                chunk = payload.get("delta", payload.get("text"))
                if chunk is not None:
                    yield chunk

    def _request_multipart(self, method: str, path: str,
                           files: Dict[str, Union[str, Tuple[str, bytes]]]) -> Any:
        """Post multipart/form-data. Each value is a plain string (a form field) or
        a (filename, bytes) tuple (a file part)."""
        boundary = "----relio" + uuid.uuid4().hex
        parts = []
        for name, val in files.items():
            parts.append(b"--" + boundary.encode() + b"\\r\\n")
            if isinstance(val, tuple):
                filename, content = val
                parts.append(
                    f'Content-Disposition: form-data; name="{name}"; filename="{filename}"\\r\\n\\r\\n'.encode()
                )
                parts.append(content if isinstance(content, bytes) else str(content).encode())
            else:
                parts.append(f'Content-Disposition: form-data; name="{name}"\\r\\n\\r\\n'.encode())
                parts.append(str(val).encode())
            parts.append(b"\\r\\n")
        parts.append(b"--" + boundary.encode() + b"--\\r\\n")
        body = b"".join(parts)
        headers = dict(self._headers(False))
        headers["Content-Type"] = "multipart/form-data; boundary=" + boundary
        req = urllib.request.Request(self.base_url + path, data=body, headers=headers, method=method)
        with urllib.request.urlopen(req) as resp:
            text = resp.read().decode()
        return json.loads(text) if text else None

    def chat(self, body: "ChatRequest") -> Iterator[str]:
        data = json.dumps(body).encode()
        req = urllib.request.Request(
            self.base_url + "/api/chat", data=data, headers=self._headers(True), method="POST"
        )
        with urllib.request.urlopen(req) as resp:
            for raw in resp:
                line = raw.decode().strip()
                if not line.startswith("data:"):
                    continue
                payload = json.loads(line[len("data:"):].strip())
                if "delta" in payload:
                    yield payload["delta"]
'''


def generate_py_client(openapi: dict) -> str:
    out = [_PY_CLIENT_PREAMBLE]
    for op in _plan_operations(openapi):
        url_expr = ('f"' + op.path + '"') if op.path_params else ('"' + op.path + '"')
        path_args = ["self"] + [f"{p}: str" for p in op.path_params]
        ret = _py_type(op.success)

        if op.kind == "multipart":
            args = path_args + ["files: Dict[str, Union[str, Tuple[str, bytes]]]"]
            out.append(
                f"    def {op.op_id}({', '.join(args)}) -> {ret}:\n"
                f'        return self._request_multipart("{op.method}", {url_expr}, files)\n'
            )
        elif op.kind == "stream":
            args = path_args + ([f'body: "{op.body_type}"'] if op.body_type else [])
            body_arg = "body" if op.body_type else "None"
            out.append(
                f"    def {op.op_id}({', '.join(args)}) -> Iterator[str]:\n"
                f'        yield from self._stream("{op.method}", {url_expr}, {body_arg})\n'
            )
        else:
            args = list(path_args)
            if op.body_type:
                args.append(f'body: "{op.body_type}"')
            for q in op.query_params:
                qt = _py_type(q.get("schema"))
                args.append(f"{q['name']}: {qt}" if q.get("required") else f"{q['name']}: {qt} = None")
            call = [f'"{op.method}"', url_expr, "body=body" if op.body_type else "body=None"]
            if op.query_params:
                qdict = ", ".join(f'"{q["name"]}": {q["name"]}' for q in op.query_params)
                call.append("query={" + qdict + "}")
            out.append(
                f"    def {op.op_id}({', '.join(args)}) -> {ret}:\n"
                f"        return self._request({', '.join(call)})\n"
            )
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# entry point
# --------------------------------------------------------------------------- #


def generate_all(openapi: dict) -> dict[str, str]:
    """Map of relative filename -> file contents for the full SDK."""
    return {
        "types.ts": generate_ts_types(openapi),
        "client.ts": generate_ts_client(openapi),
        "types.py": generate_py_types(openapi),
        "client.py": generate_py_client(openapi),
    }


def app_schema(app_spec: str = "app:app") -> dict:
    """Read the OpenAPI schema from the **user's** FastAPI app so the generated
    SDK covers their custom endpoints — not just Relio's built-ins.

    `app_spec` is `"module:attr"` (default `app:app`), imported relative to the
    current working directory. Raises if the app can't be imported — a partial
    SDK should never be shipped silently.
    """
    import importlib
    import os
    import sys

    module_name, _, attr = app_spec.partition(":")
    attr = attr or "app"
    cwd = os.getcwd()
    if cwd not in sys.path:
        sys.path.insert(0, cwd)
    # Reload if already imported (e.g. repeated runs in one process) so we read
    # the current app, not a cached one.
    if module_name in sys.modules:
        module = importlib.reload(sys.modules[module_name])
    else:
        module = importlib.import_module(module_name)
    app = getattr(module, attr)
    return app.openapi()


def reference_schema() -> dict:
    """OpenAPI for a bare Relio app (built-in routes only). Used when no user app
    exists yet — e.g. while `relio new` is scaffolding the project."""
    import os
    import tempfile

    from relio import Memory
    from relio.embedding.base import DeterministicEmbedder
    from relio.server.app import create_app
    from relio.server.llm.fake import FakeProvider

    memory = Memory(
        embedder=DeterministicEmbedder(dim=8),
        path=os.path.join(tempfile.mkdtemp(), "sdk.db"),
    )
    try:
        return create_app(memory, FakeProvider()).openapi()
    finally:
        memory.close()
