# relio/sdkgen.py
"""Generate TypeScript and Python SDKs (types + typed client) from the backend's
OpenAPI schema, so every client mirrors the one source of truth (Pydantic).

Dependency-light and offline: walks the schema dict the FastAPI app already
produces — no external codegen toolchain.
"""
from __future__ import annotations

from typing import Any

# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #


def _ref_name(schema: dict) -> str:
    return schema["$ref"].rsplit("/", 1)[-1]


def _camel(snake: str) -> str:
    head, *rest = snake.split("_")
    return head + "".join(p.capitalize() for p in rest)


def _success_response(op: dict) -> dict | None:
    for code in ("200", "201"):
        resp = op.get("responses", {}).get(code)
        if resp:
            return resp.get("content", {}).get("application/json", {}).get("schema")
    return None


# --------------------------------------------------------------------------- #
# TypeScript
# --------------------------------------------------------------------------- #


def _ts_type(schema: dict | None) -> str:
    if not schema:
        return "any"
    if "$ref" in schema:
        return _ref_name(schema)
    if "allOf" in schema:
        return _ts_type(schema["allOf"][0])
    if "anyOf" in schema:
        parts = [_ts_type(s) for s in schema["anyOf"]]
        return " | ".join(dict.fromkeys(parts))  # de-dupe, keep order
    if "enum" in schema:
        return " | ".join(_ts_literal(v) for v in schema["enum"])
    t = schema.get("type")
    if t == "array":
        return f"{_ts_type(schema.get('items'))}[]"
    if t == "object":
        return "Record<string, any>"
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    return "any"


def _ts_literal(v: Any) -> str:
    return f'"{v}"' if isinstance(v, str) else str(v)


def generate_ts_types(openapi: dict) -> str:
    schemas = openapi.get("components", {}).get("schemas", {})
    lines = ["// AUTO-GENERATED by `relio sdk`. Do not edit by hand.", ""]
    for name, schema in schemas.items():
        if "enum" in schema:
            union = " | ".join(_ts_literal(v) for v in schema["enum"])
            lines.append(f"export type {name} = {union};")
            lines.append("")
            continue
        if schema.get("type") == "object":
            required = set(schema.get("required", []))
            lines.append(f"export interface {name} {{")
            for prop, pschema in schema.get("properties", {}).items():
                opt = "" if prop in required else "?"
                lines.append(f"  {prop}{opt}: {_ts_type(pschema)};")
            lines.append("}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


_TS_CLIENT_PREAMBLE = '''\
// AUTO-GENERATED by `relio sdk`. Do not edit by hand.
import type {{ {imports} }} from "./types";

export class RelioClient {{
  constructor(private baseUrl: string = "", private apiKey?: string) {{}}

  private _headers(json: boolean): Record<string, string> {{
    const h: Record<string, string> = {{}};
    if (json) h["Content-Type"] = "application/json";
    if (this.apiKey) h["Authorization"] = `Bearer ${{this.apiKey}}`;
    return h;
  }}

  private async _request(method: string, path: string, body?: any, query?: Record<string, any>): Promise<any> {{
    let qs = "";
    if (query) {{
      const p = new URLSearchParams();
      for (const [k, v] of Object.entries(query)) if (v !== undefined && v !== null) p.set(k, String(v));
      const s = p.toString();
      if (s) qs = "?" + s;
    }}
    const res = await fetch(this.baseUrl + path + qs, {{
      method,
      headers: this._headers(body !== undefined),
      body: body !== undefined ? JSON.stringify(body) : undefined,
    }});
    if (!res.ok) throw new Error(`Relio ${{method}} ${{path}} -> ${{res.status}}`);
    const text = await res.text();
    return text ? JSON.parse(text) : null;
  }}

  async *chat(body: ChatRequest): AsyncGenerator<string> {{
    const res = await fetch(this.baseUrl + "/api/chat", {{
      method: "POST",
      headers: this._headers(true),
      body: JSON.stringify(body),
    }});
    const reader = res.body!.getReader();
    const dec = new TextDecoder();
    let buf = "";
    while (true) {{
      const {{ done, value }} = await reader.read();
      if (done) break;
      buf += dec.decode(value, {{ stream: true }});
      let i: number;
      while ((i = buf.indexOf("\\n\\n")) !== -1) {{
        const f = buf.slice(0, i).trim();
        buf = buf.slice(i + 2);
        if (!f.startsWith("data:")) continue;
        const p = JSON.parse(f.slice(f.indexOf(":") + 1).trim());
        if (p.delta) yield p.delta;
      }}
    }}
  }}
'''


def _op_inputs(path: str, op: dict) -> tuple[list[str], str | None, list[dict]]:
    """Return (path_param_names, body_type_name | None, query_params)."""
    path_params = [
        p["name"] for p in op.get("parameters", []) if p.get("in") == "path"
    ]
    query_params = [p for p in op.get("parameters", []) if p.get("in") == "query"]
    body_type = None
    rb = op.get("requestBody")
    if rb:
        schema = rb.get("content", {}).get("application/json", {}).get("schema", {})
        if "$ref" in schema:
            body_type = _ref_name(schema)
    return path_params, body_type, query_params


def generate_ts_client(openapi: dict) -> str:
    schemas = openapi.get("components", {}).get("schemas", {})
    imports = ", ".join(sorted(schemas.keys()))
    out = [_TS_CLIENT_PREAMBLE.format(imports=imports)]
    for path, item in openapi.get("paths", {}).items():
        for method, op in item.items():
            op_id = op.get("operationId")
            if not op_id or op_id == "chat":
                continue
            path_params, body_type, query_params = _op_inputs(path, op)
            args: list[str] = [f"{_camel(p)}: string" for p in path_params]
            if body_type:
                args.append(f"body: {body_type}")
            if query_params:
                fields = []
                for q in query_params:
                    opt = "" if q.get("required") else "?"
                    fields.append(f"{q['name']}{opt}: {_ts_type(q.get('schema'))}")
                args.append("query: { " + "; ".join(fields) + " }")
            url = path
            for p in path_params:
                url = url.replace("{" + p + "}", "${" + _camel(p) + "}")
            ret = _ts_type(_success_response(op))
            call = [f'"{method.upper()}"', f"`{url}`"]
            call.append("body" if body_type else "undefined")
            if query_params:
                call.append("query")
            out.append(
                f"  async {_camel(op_id)}({', '.join(args)}): Promise<{ret}> {{\n"
                f"    return this._request({', '.join(call)});\n"
                f"  }}\n"
            )
    out.append("}\n")
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# Python
# --------------------------------------------------------------------------- #


def _py_type(schema: dict | None) -> str:
    if not schema:
        return "Any"
    if "$ref" in schema:
        return f'"{_ref_name(schema)}"'
    if "allOf" in schema:
        return _py_type(schema["allOf"][0])
    if "anyOf" in schema:
        parts = [s for s in schema["anyOf"] if s.get("type") != "null"]
        inner = " | ".join(dict.fromkeys(_py_type(s) for s in parts)) or "Any"
        if any(s.get("type") == "null" for s in schema["anyOf"]):
            return f"Optional[{inner}]"
        return inner
    if "enum" in schema:
        return "Literal[" + ", ".join(repr(v) for v in schema["enum"]) + "]"
    t = schema.get("type")
    if t == "array":
        return f"List[{_py_type(schema.get('items'))}]"
    if t == "object":
        return "Dict[str, Any]"
    if t == "string":
        return "str"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "null":
        return "None"
    return "Any"


def generate_py_types(openapi: dict) -> str:
    schemas = openapi.get("components", {}).get("schemas", {})
    lines = [
        "# AUTO-GENERATED by `relio sdk`. Do not edit by hand.",
        "from __future__ import annotations",
        "",
        "from typing import Any, Dict, List, Literal, Optional, TypedDict",
        "",
    ]
    for name, schema in schemas.items():
        if "enum" in schema:
            union = ", ".join(repr(v) for v in schema["enum"])
            lines.append(f"{name} = Literal[{union}]")
            lines.append("")
            continue
        if schema.get("type") == "object":
            lines.append(f"class {name}(TypedDict, total=False):")
            props = schema.get("properties", {})
            if not props:
                lines.append("    pass")
            for prop, pschema in props.items():
                lines.append(f"    {prop}: {_py_type(pschema)}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


_PY_CLIENT_PREAMBLE = '''\
# AUTO-GENERATED by `relio sdk`. Do not edit by hand.
from __future__ import annotations

import json
import urllib.parse
import urllib.request
from typing import Any, Dict, Iterator, Optional


class RelioClient:
    def __init__(self, base_url: str = "http://localhost:8000", api_key: Optional[str] = None) -> None:
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key

    def _headers(self, json_body: bool) -> Dict[str, str]:
        h: Dict[str, str] = {}
        if json_body:
            h["Content-Type"] = "application/json"
        if self.api_key:
            h["Authorization"] = f"Bearer {self.api_key}"
        return h

    def _request(self, method: str, path: str, body: Any = None, query: Optional[Dict[str, Any]] = None) -> Any:
        url = self.base_url + path
        if query:
            clean = {k: v for k, v in query.items() if v is not None}
            if clean:
                url += "?" + urllib.parse.urlencode(clean)
        data = json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(url, data=data, headers=self._headers(body is not None), method=method)
        with urllib.request.urlopen(req) as resp:
            text = resp.read().decode()
        return json.loads(text) if text else None

    def chat(self, body: "ChatRequest") -> Iterator[str]:
        data = json.dumps(body).encode()
        req = urllib.request.Request(
            self.base_url + "/api/chat", data=data, headers=self._headers(True), method="POST"
        )
        with urllib.request.urlopen(req) as resp:
            for raw in resp:
                line = raw.decode().strip()
                if not line.startswith("data:"):
                    continue
                payload = json.loads(line[len("data:"):].strip())
                if "delta" in payload:
                    yield payload["delta"]
'''


def generate_py_client(openapi: dict) -> str:
    out = [_PY_CLIENT_PREAMBLE]
    for path, item in openapi.get("paths", {}).items():
        for method, op in item.items():
            op_id = op.get("operationId")
            if not op_id or op_id == "chat":
                continue
            path_params, body_type, query_params = _op_inputs(path, op)
            args = ["self"] + [f"{p}: str" for p in path_params]
            if body_type:
                args.append(f'body: "{body_type}"')
            for q in query_params:
                qt = _py_type(q.get("schema"))
                if q.get("required"):
                    args.append(f"{q['name']}: {qt}")
                else:
                    args.append(f"{q['name']}: {qt} = None")
            url_expr = '"' + path + '"'
            if path_params:
                url_expr = 'f"' + path + '"'
            call = [f'"{method.upper()}"', url_expr]
            call.append("body=body" if body_type else "body=None")
            if query_params:
                qdict = ", ".join(f'"{q["name"]}": {q["name"]}' for q in query_params)
                call.append("query={" + qdict + "}")
            ret = _py_type(_success_response(op))
            out.append(
                f"    def {op_id}({', '.join(args)}) -> {ret}:\n"
                f"        return self._request({', '.join(call)})\n"
            )
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# entry point
# --------------------------------------------------------------------------- #


def generate_all(openapi: dict) -> dict[str, str]:
    """Map of relative filename -> file contents for the full SDK."""
    return {
        "types.ts": generate_ts_types(openapi),
        "client.ts": generate_ts_client(openapi),
        "types.py": generate_py_types(openapi),
        "client.py": generate_py_client(openapi),
    }


def app_schema() -> dict:
    """Build a throwaway app purely to read its static OpenAPI schema."""
    import os
    import tempfile

    from relio import Memory
    from relio.embedding.base import DeterministicEmbedder
    from relio.server.app import create_app
    from relio.server.llm.fake import FakeProvider

    memory = Memory(
        embedder=DeterministicEmbedder(dim=8),
        path=os.path.join(tempfile.mkdtemp(), "sdk.db"),
    )
    try:
        return create_app(memory, FakeProvider()).openapi()
    finally:
        memory.close()
